[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 4000

ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/"}, 
    { access = "read", path = "./artifacts/"}, 
    { access = "read", path = "./out/"}, 
    { access = "read-write", path = "./addresses.json"}
]

# Metadata configuration for contract verification
metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

[fmt]
line_length = 120
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config 